require("Kdm/Util/Check")
local Log = require("Kdm/Util/Log").ForPackage("Armor")

local Armor = {
    armorStats = {}
}

---------------------------------------------------------------------------------------------------

function Armor.RegisterExpansion(expansion)
    for armor, stats in pairs(expansion.armorStats or {}) do
        assert(Check(Armor.armorStats[armor] == nil, "Armor %s is already registered", armor))
        Armor.armorStats[armor] = stats
    end
end

---------------------------------------------------------------------------------------------------

function Armor.GetStats(armor)
    return Armor.armorStats[armor]
end

---------------------------------------------------------------------------------------------------

return Armor
