local Assert = require("Kdm/Util/Assert")

local Weapons = {
    weaponStats = {}
}

---------------------------------------------------------------------------------------------------

function Weapons.RegisterWeaponStats(weaponStats)
    for weapon, stats in pairs(weaponStats or {}) do
        Assert(Weapons.weaponStats[weapon] == nil, "Weapon %s is already registered", weapon)
        Weapons.weaponStats[weapon] = stats
    end
end

---------------------------------------------------------------------------------------------------

function Weapons.GetStats(weapon)
    return Weapons.weaponStats[weapon]
end

---------------------------------------------------------------------------------------------------

return Weapons
