require("Kdm/Util/Check")

local Weapons = {
    weaponStats = {}
}

---------------------------------------------------------------------------------------------------

function Weapons.RegisterExpansion(expansion)
    for weapon, stats in pairs(expansion.weaponStats or {}) do
        assert(Check(Weapons.weaponStats[weapon] == nil, "Weapon %s is already registered", weapon))
        Weapons.weaponStats[weapon] = stats
    end
end

---------------------------------------------------------------------------------------------------

function Weapons.GetStats(weapon)
    return Weapons.weaponStats[weapon]
end

---------------------------------------------------------------------------------------------------

return Weapons
