require("Kdm/Util/Check")

local Weapon_stats = {}

---------------------------------------------------------------------------------------------------

local function Weapon_Init(saveState, expansion, deps)
    for _, expansion in ipairs(expansions) do
        for weapon, stats in pairs(expansion.weaponStats or {}) do
            assert(Check(Weapon_stats[weapon] == nil, "Weapon %s is already registered", weapon))
            Weapon_stats[weapon] = stats
        end
    end
end

---------------------------------------------------------------------------------------------------

function Weapon_Get(weapon)
    return Weapon_stats[weapon]
end

---------------------------------------------------------------------------------------------------

return {
    Init = Weapon_Init,
    Get = Weapon_Get,
}
